" Name:         Tonight
" Description:  Never put off till tomorrow what you can do tonight
" Author:       jnnl <juho@jnnl.eu>
" Maintainer:   jnnl <juho@jnnl.eu>
" Website:      https://github.com/jnnl/vim-tonight
" License:      MIT
" Last Updated: Tue 10 Mar 2020 12:12:33 PM EET

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'tonight'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#262626', '#d75f5f', '#d7875f', '#afaf5f',
        \ '#87afaf', '#5fd7d7', '#af87af', '#c6c6c6', '#444444', '#5f0000',
        \ '#875f00', '#005f00', '#005f5f', '#5f005f', '#008787', '#dadada']
  if has('nvim')
    let g:terminal_color_0 = '#262626'
    let g:terminal_color_1 = '#d75f5f'
    let g:terminal_color_2 = '#d7875f'
    let g:terminal_color_3 = '#afaf5f'
    let g:terminal_color_4 = '#87afaf'
    let g:terminal_color_5 = '#5fd7d7'
    let g:terminal_color_6 = '#af87af'
    let g:terminal_color_7 = '#c6c6c6'
    let g:terminal_color_8 = '#444444'
    let g:terminal_color_9 = '#5f0000'
    let g:terminal_color_10 = '#875f00'
    let g:terminal_color_11 = '#005f00'
    let g:terminal_color_12 = '#005f5f'
    let g:terminal_color_13 = '#5f005f'
    let g:terminal_color_14 = '#008787'
    let g:terminal_color_15 = '#dadada'
  endif
  if get(g:, 'tonight_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#c6c6c6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#c6c6c6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#c6c6c6 guibg=#262626 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#c6c6c6 guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  endif
  hi! link Boolean Constant
  hi! link Character Constant
  hi ColorColumn guifg=#c6c6c6 guibg=#444444 guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#808080 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#c6c6c6 guibg=#444444 guisp=NONE gui=NONE cterm=NONE
  hi! link Conditional Statement
  hi Constant guifg=#d7875f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi! link CursorColumn CursorLine
  hi CursorLine guifg=#c6c6c6 guibg=#444444 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#626262 guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi! link Debug Special
  hi! link Define Statement
  hi! link Delimiter Special
  hi DiffAdd guifg=#dadada guibg=#005f00 guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#444444 guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=#5f0000 guibg=#5f0000 guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#005f5f guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#87afaf guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#444444 guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#d75f5f guibg=NONE guisp=NONE gui=underline cterm=underline
  hi ErrorMsg guifg=#dadada guibg=#5f0000 guisp=NONE gui=NONE cterm=NONE
  hi! link Exception Statement
  hi! link Float Constant
  hi FoldColumn guifg=#c6c6c6 guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#808080 guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi! link Function Identifier
  hi Identifier guifg=#87afaf guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#626262 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#262626 guibg=#d7875f guisp=NONE gui=NONE cterm=NONE
  hi! link Include Statement
  hi! link Keyword Statement
  hi! link Label Statement
  hi LineNr guifg=#444444 guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi! link Macro Statement
  hi MatchParen guifg=NONE guibg=#444444 guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#afaf5f guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#afaf5f guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#626262 guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi Normal guifg=#c6c6c6 guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi! link Number Constant
  hi! link Operator Statement
  hi Pmenu guifg=#c6c6c6 guibg=#626262 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#808080 guibg=#808080 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#626262 guibg=#c6c6c6 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#808080 guibg=#626262 guisp=NONE gui=NONE cterm=NONE
  hi! link PreCondit Statement
  hi! link PreProc Statement
  hi Question guifg=#afaf5f guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi QuickFixLine guifg=#262626 guibg=#d7af87 guisp=NONE gui=NONE cterm=NONE
  hi! link Repeat Statement
  hi Search guifg=#262626 guibg=#d7af87 guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#c6c6c6 guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#c6c6c6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi SpecialKey guifg=#626262 guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#d75f5f guibg=#262626 guisp=NONE gui=italic cterm=italic
  hi SpellCap guifg=#87afaf guibg=#262626 guisp=NONE gui=italic cterm=italic
  hi SpellLocal guifg=#afaf5f guibg=#262626 guisp=NONE gui=italic cterm=italic
  hi SpellRare guifg=#d7af87 guibg=#262626 guisp=NONE gui=italic cterm=italic
  hi Statement guifg=#af87af guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#d7af87 guibg=#444444 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#c6c6c6 guibg=#444444 guisp=NONE gui=NONE cterm=NONE
  hi! link StorageClass Type
  hi String guifg=#afaf5f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link Structure Type
  hi TabLine guifg=#c6c6c6 guibg=#444444 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#c6c6c6 guibg=#444444 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#d7af87 guibg=#444444 guisp=NONE gui=NONE cterm=NONE
  hi! link Tag Special
  hi Title guifg=#808080 guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#d7875f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#d7af87 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link Typedef Type
  hi Underlined guifg=#c6c6c6 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi VertSplit guifg=#444444 guibg=#444444 guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#444444 guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#d75f5f guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#262626 guibg=#d7af87 guisp=NONE gui=NONE cterm=NONE
  hi NormalFloat guifg=#c6c6c6 guibg=#444444 guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi SpellBad gui=NONE cterm=NONE
    hi SpellCap gui=NONE cterm=NONE
    hi SpellLocal gui=NONE cterm=NONE
    hi SpellRare gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'tonight_transp_bg', 0)
    hi Normal ctermfg=251 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=251 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=251 ctermbg=235 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=251 ctermbg=235 cterm=NONE
  endif
  hi! link Boolean Constant
  hi! link Character Constant
  hi ColorColumn ctermfg=251 ctermbg=238 cterm=NONE
  hi Comment ctermfg=244 ctermbg=NONE cterm=NONE
  hi Conceal ctermfg=251 ctermbg=238 cterm=NONE
  hi! link Conditional Statement
  hi Constant ctermfg=173 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi! link CursorColumn CursorLine
  hi CursorLine ctermfg=251 ctermbg=238 cterm=NONE
  hi CursorLineNr ctermfg=241 ctermbg=235 cterm=NONE
  hi! link Debug Special
  hi! link Define Statement
  hi! link Delimiter Special
  hi DiffAdd ctermfg=253 ctermbg=22 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=238 cterm=NONE
  hi DiffDelete ctermfg=52 ctermbg=52 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=23 cterm=NONE
  hi Directory ctermfg=109 ctermbg=235 cterm=NONE
  hi EndOfBuffer ctermfg=238 ctermbg=235 cterm=NONE
  hi Error ctermfg=167 ctermbg=NONE cterm=underline
  hi ErrorMsg ctermfg=253 ctermbg=52 cterm=NONE
  hi! link Exception Statement
  hi! link Float Constant
  hi FoldColumn ctermfg=251 ctermbg=235 cterm=NONE
  hi Folded ctermfg=244 ctermbg=235 cterm=NONE
  hi! link Function Identifier
  hi Identifier ctermfg=109 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=241 ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=235 ctermbg=173 cterm=NONE
  hi! link Include Statement
  hi! link Keyword Statement
  hi! link Label Statement
  hi LineNr ctermfg=238 ctermbg=235 cterm=NONE
  hi! link Macro Statement
  hi MatchParen ctermfg=NONE ctermbg=238 cterm=NONE
  hi ModeMsg ctermfg=143 ctermbg=235 cterm=NONE
  hi MoreMsg ctermfg=143 ctermbg=235 cterm=NONE
  hi NonText ctermfg=241 ctermbg=235 cterm=NONE
  hi Normal ctermfg=251 ctermbg=235 cterm=NONE
  if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
    set background=dark
  endif
  hi! link Number Constant
  hi! link Operator Statement
  hi Pmenu ctermfg=251 ctermbg=241 cterm=NONE
  hi PmenuSbar ctermfg=244 ctermbg=244 cterm=NONE
  hi PmenuSel ctermfg=241 ctermbg=251 cterm=NONE
  hi PmenuThumb ctermfg=244 ctermbg=241 cterm=NONE
  hi! link PreCondit Statement
  hi! link PreProc Statement
  hi Question ctermfg=143 ctermbg=235 cterm=NONE
  hi QuickFixLine ctermfg=235 ctermbg=180 cterm=NONE
  hi! link Repeat Statement
  hi Search ctermfg=235 ctermbg=180 cterm=NONE
  hi SignColumn ctermfg=251 ctermbg=235 cterm=NONE
  hi Special ctermfg=251 ctermbg=NONE cterm=NONE
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi SpecialKey ctermfg=241 ctermbg=235 cterm=NONE
  hi SpellBad ctermfg=167 ctermbg=235 cterm=italic
  hi SpellCap ctermfg=109 ctermbg=235 cterm=italic
  hi SpellLocal ctermfg=143 ctermbg=235 cterm=italic
  hi SpellRare ctermfg=180 ctermbg=235 cterm=italic
  hi Statement ctermfg=139 ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=180 ctermbg=238 cterm=NONE
  hi StatusLineNC ctermfg=251 ctermbg=238 cterm=NONE
  hi! link StorageClass Type
  hi String ctermfg=143 ctermbg=NONE cterm=NONE
  hi! link Structure Type
  hi TabLine ctermfg=251 ctermbg=238 cterm=NONE
  hi TabLineFill ctermfg=251 ctermbg=238 cterm=NONE
  hi TabLineSel ctermfg=180 ctermbg=238 cterm=NONE
  hi! link Tag Special
  hi Title ctermfg=244 ctermbg=235 cterm=NONE
  hi Todo ctermfg=173 ctermbg=NONE cterm=NONE
  hi Type ctermfg=180 ctermbg=NONE cterm=NONE
  hi! link Typedef Type
  hi Underlined ctermfg=251 ctermbg=NONE cterm=underline
  hi VertSplit ctermfg=238 ctermbg=238 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=238 cterm=NONE
  hi WarningMsg ctermfg=167 ctermbg=235 cterm=NONE
  hi WildMenu ctermfg=235 ctermbg=180 cterm=NONE
  hi NormalFloat ctermfg=251 ctermbg=238 cterm=NONE
  if !s:italics
    hi SpellBad cterm=NONE
    hi SpellCap cterm=NONE
    hi SpellLocal cterm=NONE
    hi SpellRare cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'tonight_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi! link Boolean Constant
  hi! link Character Constant
  hi ColorColumn ctermfg=White ctermbg=LightGrey cterm=NONE
  hi Comment ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Conceal ctermfg=White ctermbg=LightGrey cterm=NONE
  hi! link Conditional Statement
  hi Constant ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi! link CursorColumn CursorLine
  hi CursorLine ctermfg=White ctermbg=LightGrey cterm=NONE
  hi CursorLineNr ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi! link Debug Special
  hi! link Define Statement
  hi! link Delimiter Special
  hi DiffAdd ctermfg=LightGrey ctermbg=DarkGreen cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi DiffDelete ctermfg=DarkRed ctermbg=DarkRed cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=DarkBlue cterm=NONE
  hi Directory ctermfg=Blue ctermbg=Black cterm=NONE
  hi EndOfBuffer ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Error ctermfg=Red ctermbg=NONE cterm=underline
  hi ErrorMsg ctermfg=LightGrey ctermbg=DarkRed cterm=NONE
  hi! link Exception Statement
  hi! link Float Constant
  hi FoldColumn ctermfg=White ctermbg=Black cterm=NONE
  hi Folded ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi! link Function Identifier
  hi Identifier ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=Black ctermbg=Yellow cterm=NONE
  hi! link Include Statement
  hi! link Keyword Statement
  hi! link Label Statement
  hi LineNr ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi! link Macro Statement
  hi MatchParen ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi ModeMsg ctermfg=Green ctermbg=Black cterm=NONE
  hi MoreMsg ctermfg=Green ctermbg=Black cterm=NONE
  hi NonText ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Normal ctermfg=White ctermbg=Black cterm=NONE
  hi! link Number Constant
  hi! link Operator Statement
  hi Pmenu ctermfg=White ctermbg=LightGrey cterm=NONE
  hi PmenuSbar ctermfg=LightGrey ctermbg=LightGrey cterm=NONE
  hi PmenuSel ctermfg=LightGrey ctermbg=White cterm=NONE
  hi PmenuThumb ctermfg=LightGrey ctermbg=LightGrey cterm=NONE
  hi! link PreCondit Statement
  hi! link PreProc Statement
  hi Question ctermfg=Green ctermbg=Black cterm=NONE
  hi QuickFixLine ctermfg=Black ctermbg=Yellow cterm=NONE
  hi! link Repeat Statement
  hi Search ctermfg=Black ctermbg=Yellow cterm=NONE
  hi SignColumn ctermfg=White ctermbg=Black cterm=NONE
  hi Special ctermfg=White ctermbg=NONE cterm=NONE
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi SpecialKey ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpellBad ctermfg=Red ctermbg=Black cterm=italic
  hi SpellCap ctermfg=Blue ctermbg=Black cterm=italic
  hi SpellLocal ctermfg=Green ctermbg=Black cterm=italic
  hi SpellRare ctermfg=Yellow ctermbg=Black cterm=italic
  hi Statement ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=Yellow ctermbg=LightGrey cterm=NONE
  hi StatusLineNC ctermfg=White ctermbg=LightGrey cterm=NONE
  hi! link StorageClass Type
  hi String ctermfg=Green ctermbg=NONE cterm=NONE
  hi! link Structure Type
  hi TabLine ctermfg=White ctermbg=LightGrey cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=LightGrey cterm=NONE
  hi TabLineSel ctermfg=Yellow ctermbg=LightGrey cterm=NONE
  hi! link Tag Special
  hi Title ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Todo ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi! link Typedef Type
  hi Underlined ctermfg=White ctermbg=NONE cterm=underline
  hi VertSplit ctermfg=LightGrey ctermbg=LightGrey cterm=NONE
  hi Visual ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi WarningMsg ctermfg=Red ctermbg=Black cterm=NONE
  hi WildMenu ctermfg=Black ctermbg=Yellow cterm=NONE
  hi NormalFloat ctermfg=White ctermbg=LightGrey cterm=NONE
  if !s:italics
    hi SpellBad cterm=NONE
    hi SpellCap cterm=NONE
    hi SpellLocal cterm=NONE
    hi SpellRare cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: foreground   #c6c6c6 ~ White
" Color: background   #262626 ~ Black
" Color: grey0        #444444 ~ LightGrey
" Color: grey1        #626262 ~ LightGrey
" Color: grey2        #808080 ~ LightGrey
" Color: grey3        #dadada ~ LightGrey
" Color: red          #d75f5f ~ Red
" Color: dark_red     #5f0000 ~ DarkRed
" Color: orange       #d7875f ~ Yellow
" Color: light_orange #d7af87 ~ Yellow
" Color: dark_orange  #875f00 ~ Yellow
" Color: green        #afaf5f ~ Green
" Color: dark_green   #005f00 ~ DarkGreen
" Color: blue         #87afaf ~ Blue
" Color: dark_blue    #005f5f ~ DarkBlue
" Color: cyan         #5fd7d7 ~ Cyan
" Color: dark_cyan    #008787 ~ DarkCyan
" Color: purple       #af87af ~ Magenta
" Color: dark_purple  #5f005f ~ DarkMagenta
" Term colors: background red orange green blue cyan purple foreground
" Term colors: grey0 dark_red dark_orange dark_green
" Term colors: dark_blue dark_purple dark_cyan grey3
" vim: et ts=2 sw=2
